"""Network management API — interfaces, DNS, IP configuration."""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required
from utils.command import run_host_command
import psutil

network_bp = Blueprint("network", __name__)


def get_active_manager():
    """Detect if NetworkManager or systemd-networkd/netplan is active."""
    nm_check = run_host_command("systemctl is-active NetworkManager")
    if nm_check["stdout"].strip() == "active":
        return "NetworkManager"
    
    networkd_check = run_host_command("systemctl is-active systemd-networkd")
    if networkd_check["stdout"].strip() == "active":
        return "systemd-networkd"
    
    return "unknown"


@network_bp.route("/status", methods=["GET"])
@jwt_required()
def network_status():
    """Get info about the network management system."""
    manager = get_active_manager()
    has_nmcli = run_host_command("which nmcli")["returncode"] == 0
    has_netplan = run_host_command("which netplan")["returncode"] == 0
    
    return jsonify({
        "manager": manager,
        "has_nmcli": has_nmcli,
        "has_netplan": has_netplan
    })


@network_bp.route("/interfaces", methods=["GET"])
@jwt_required()
def list_interfaces():
    """List network interfaces with their addresses."""
    interfaces = []
    addrs = psutil.net_if_addrs()
    stats = psutil.net_if_stats()

    for iface_name, addr_list in addrs.items():
        iface = {
            "name": iface_name,
            "addresses": [],
            "is_up": stats.get(iface_name, None) and stats[iface_name].isup,
            "speed": stats[iface_name].speed if iface_name in stats else 0,
            "mtu": stats[iface_name].mtu if iface_name in stats else 0,
        }
        for addr in addr_list:
            iface["addresses"].append({
                "family": str(addr.family.name) if hasattr(addr.family, 'name') else str(addr.family),
                "address": addr.address,
                "netmask": addr.netmask,
                "broadcast": addr.broadcast,
            })
        interfaces.append(iface)

    return jsonify({"interfaces": interfaces})


@network_bp.route("/dns", methods=["GET"])
@jwt_required()
def get_dns():
    """Get DNS configuration."""
    result = run_host_command("cat /etc/resolv.conf")
    nameservers = []
    if result["stdout"]:
        for line in result["stdout"].split("\n"):
            if line.strip().startswith("nameserver"):
                ns = line.strip().split(None, 1)
                if len(ns) > 1:
                    nameservers.append(ns[1])

    return jsonify({"nameservers": nameservers, "raw": result["stdout"]})


@network_bp.route("/dns", methods=["PUT"])
@jwt_required()
def set_dns():
    """Set DNS nameservers."""
    data = request.get_json()
    nameservers = data.get("nameservers", [])

    content = "# Generated by EasyLin\n"
    for ns in nameservers:
        content += f"nameserver {ns}\n"

    result = run_host_command(f"echo '{content}' > /etc/resolv.conf")
    return jsonify({"success": result["returncode"] == 0})


@network_bp.route("/connections", methods=["GET"])
@jwt_required()
def list_connections():
    """List active network connections."""
    result = run_host_command("ss -tulnp 2>/dev/null | head -50")
    return jsonify({"output": result["stdout"]})


@network_bp.route("/interfaces/<iface>/config", methods=["GET"])
@jwt_required()
def get_interface_config(iface):
    """Get both LIVE and SAVED configuration for an interface."""
    # 1. LIVE DATA (from psutil/OS)
    addrs = psutil.net_if_addrs().get(iface, [])
    live_ip = ""
    for addr in addrs:
        if addr.family.name == 'AF_INET':
            live_ip = f"{addr.address}/{addr.netmask}" # Semplificato
            break
            
    # 2. SAVED DATA (from Netplan/NetworkManager)
    saved = {"dhcp": True, "address": "", "gateway": "", "dns": ""}
    manager = get_active_manager()
    
    try:
        import yaml
        # Controlliamo i file netplan in ordine di priorità
        for f in ["/etc/netplan/99-easylin.yaml", "/etc/netplan/01-netcfg.yaml", "/etc/netplan/50-cloud-init.yaml"]:
            res = run_host_command(f"cat {f}")
            if res["returncode"] == 0:
                cfg = yaml.safe_load(res["stdout"])
                if "network" in cfg and "ethernets" in cfg["network"] and iface in cfg["network"]["ethernets"]:
                    ifc = cfg["network"]["ethernets"][iface]
                    saved = {
                        "dhcp": ifc.get("dhcp4") == "yes" or ifc.get("dhcp4", True) is True,
                        "address": ifc.get("addresses", [""])[0],
                        "gateway": ifc.get("routes", [{}])[0].get("via", "") if ifc.get("routes") else "",
                        "dns": ", ".join(ifc.get("nameservers", {}).get("addresses", []))
                    }
                    break
    except:
        pass

    return jsonify({
        "live": {"address": live_ip},
        "saved": saved,
        "manager": manager
    })


@network_bp.route("/interfaces/<iface>/config", methods=["POST"])
@jwt_required()
def configure_interface(iface):
    """Configure a network interface (DHCP or Static)."""
    data = request.get_json()
    use_dhcp = data.get("dhcp", True)
    address = data.get("address", "")  # e.g., 192.168.1.100/24
    gateway = data.get("gateway", "")
    dns = data.get("dns", ["8.8.8.8", "1.1.1.1"])

    manager = get_active_manager()

    # --- STRATEGY 1: NetworkManager (nmcli) ---
    if manager == "NetworkManager":
        # Check if we have a connection for this interface
        conn_res = run_host_command(f"nmcli -t -f DEVICE,NAME connection show --active | grep '^{iface}:'")
        if conn_res["returncode"] == 0:
            conn_name = conn_res["stdout"].split(":")[1]
        else:
            # Try to find any connection for this device
            conn_res = run_host_command(f"nmcli -t -f DEVICE,NAME connection show | grep '^{iface}:'")
            conn_name = conn_res["stdout"].split(":")[1] if conn_res["returncode"] == 0 else iface

        if use_dhcp:
            cmd = f"nmcli connection modify '{conn_name}' ipv4.method auto"
        else:
            dns_str = " ".join(dns)
            cmd = (
                f"nmcli connection modify '{conn_name}' "
                f"ipv4.method manual ipv4.addresses {address} "
                f"ipv4.gateway {gateway} ipv4.dns '{dns_str}'"
            )
        
        mod_res = run_host_command(cmd)
        if mod_res["returncode"] != 0:
            return jsonify({"error": f"nmcli modify failed: {mod_res['stderr']}"}), 500
        
        # Apply changes (up the connection)
        up_res = run_host_command(f"nmcli connection up '{conn_name}'")
        return jsonify({
            "success": up_res["returncode"] == 0,
            "message": "Configuration applied via NetworkManager.",
            "output": up_res["stdout"]
        })

    # --- STRATEGY 2: Netplan ---
    renderer = "NetworkManager" if manager == "NetworkManager" else "networkd"
    
    config = {
        "network": {
            "version": 2,
            "renderer": renderer,
            "ethernets": {
                iface: {
                    "dhcp4": "yes" if use_dhcp else "no",
                    "critical": True
                }
            }
        }
    }

    if not use_dhcp:
        config["network"]["ethernets"][iface]["addresses"] = [address]
        if gateway:
            config["network"]["ethernets"][iface]["routes"] = [{"to": "default", "via": gateway}]
        if dns:
            config["network"]["ethernets"][iface]["nameservers"] = {"addresses": dns}

    import yaml
    yaml_content = yaml.dump(config, default_flow_style=False)
    
    # Rimuoviamo conflitti
    run_host_command("rm -f /etc/netplan/50-cloud-init.yaml")
    
    file_path = "/etc/netplan/99-easylin.yaml"
    write_res = run_host_command(f"cat > {file_path} << 'EOF'\n{yaml_content}\nEOF")

    if write_res["returncode"] != 0:
        return jsonify({"error": f"Failed to write netplan: {write_res['stderr']}"}), 500

    # APPLICAZIONE AGGRESSIVA
    # 1. Tentativo standard
    run_host_command("netplan generate && netplan apply", timeout=15)
    
    # 2. Se è statico, forziamo l'IP direttamente via kernel (soluzione definitiva)
    if not use_dhcp:
        # Puliamo i vecchi IP (pericoloso ma necessario per la coerenza)
        run_host_command(f"ip addr flush dev {iface}")
        # Aggiungiamo il nuovo IP
        run_host_command(f"ip addr add {address} dev {iface}")
        # Tiriamo su l'interfaccia
        run_host_command(f"ip link set {iface} up")
        # Aggiungiamo il gateway
        if gateway:
            run_host_command(f"ip route add default via {gateway} dev {iface}")
    else:
        # Se è DHCP, forziamo il rinnovo
        run_host_command(f"dhclient -r {iface} && dhclient {iface}")

    return jsonify({
        "success": True,
        "message": "COMMAND FORCED: The IP has been pushed directly to the kernel. Reconnect to the new IP now.",
    })


@network_bp.route("/ping", methods=["POST"])
@jwt_required()
def ping_host():
    """Ping a host."""
    data = request.get_json()
    host = data.get("host", "").strip()
    if not host:
        return jsonify({"error": "Host is required"}), 400

    result = run_host_command(f"ping -c 4 -W 2 {host}", timeout=15)
    return jsonify({
        "success": result["returncode"] == 0,
        "output": result["stdout"],
    })
