"""Network management API — interfaces, DNS, IP configuration."""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required
from utils.command import run_host_command
import psutil

network_bp = Blueprint("network", __name__)


@network_bp.route("/interfaces", methods=["GET"])
@jwt_required()
def list_interfaces():
    """List network interfaces with their addresses."""
    interfaces = []
    addrs = psutil.net_if_addrs()
    stats = psutil.net_if_stats()

    for iface_name, addr_list in addrs.items():
        iface = {
            "name": iface_name,
            "addresses": [],
            "is_up": stats.get(iface_name, None) and stats[iface_name].isup,
            "speed": stats[iface_name].speed if iface_name in stats else 0,
            "mtu": stats[iface_name].mtu if iface_name in stats else 0,
        }
        for addr in addr_list:
            iface["addresses"].append({
                "family": str(addr.family.name) if hasattr(addr.family, 'name') else str(addr.family),
                "address": addr.address,
                "netmask": addr.netmask,
                "broadcast": addr.broadcast,
            })
        interfaces.append(iface)

    return jsonify({"interfaces": interfaces})


@network_bp.route("/dns", methods=["GET"])
@jwt_required()
def get_dns():
    """Get DNS configuration."""
    result = run_host_command("cat /etc/resolv.conf")
    nameservers = []
    if result["stdout"]:
        for line in result["stdout"].split("\n"):
            if line.strip().startswith("nameserver"):
                ns = line.strip().split(None, 1)
                if len(ns) > 1:
                    nameservers.append(ns[1])

    return jsonify({"nameservers": nameservers, "raw": result["stdout"]})


@network_bp.route("/dns", methods=["PUT"])
@jwt_required()
def set_dns():
    """Set DNS nameservers."""
    data = request.get_json()
    nameservers = data.get("nameservers", [])

    content = "# Generated by EasyLin\n"
    for ns in nameservers:
        content += f"nameserver {ns}\n"

    result = run_host_command(f"echo '{content}' > /etc/resolv.conf")
    return jsonify({"success": result["returncode"] == 0})


@network_bp.route("/connections", methods=["GET"])
@jwt_required()
def list_connections():
    """List active network connections."""
    result = run_host_command("ss -tulnp 2>/dev/null | head -50")
    return jsonify({"output": result["stdout"]})


@network_bp.route("/ping", methods=["POST"])
@jwt_required()
def ping_host():
    """Ping a host."""
    data = request.get_json()
    host = data.get("host", "").strip()
    if not host:
        return jsonify({"error": "Host is required"}), 400

    result = run_host_command(f"ping -c 4 -W 2 {host}", timeout=15)
    return jsonify({
        "success": result["returncode"] == 0,
        "output": result["stdout"],
    })
