"""Network management API — interfaces, DNS, IP configuration."""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required
from utils.command import run_host_command
import psutil

network_bp = Blueprint("network", __name__)


@network_bp.route("/interfaces", methods=["GET"])
@jwt_required()
def list_interfaces():
    """List network interfaces with their addresses."""
    interfaces = []
    addrs = psutil.net_if_addrs()
    stats = psutil.net_if_stats()

    for iface_name, addr_list in addrs.items():
        iface = {
            "name": iface_name,
            "addresses": [],
            "is_up": stats.get(iface_name, None) and stats[iface_name].isup,
            "speed": stats[iface_name].speed if iface_name in stats else 0,
            "mtu": stats[iface_name].mtu if iface_name in stats else 0,
        }
        for addr in addr_list:
            iface["addresses"].append({
                "family": str(addr.family.name) if hasattr(addr.family, 'name') else str(addr.family),
                "address": addr.address,
                "netmask": addr.netmask,
                "broadcast": addr.broadcast,
            })
        interfaces.append(iface)

    return jsonify({"interfaces": interfaces})


@network_bp.route("/dns", methods=["GET"])
@jwt_required()
def get_dns():
    """Get DNS configuration."""
    result = run_host_command("cat /etc/resolv.conf")
    nameservers = []
    if result["stdout"]:
        for line in result["stdout"].split("\n"):
            if line.strip().startswith("nameserver"):
                ns = line.strip().split(None, 1)
                if len(ns) > 1:
                    nameservers.append(ns[1])

    return jsonify({"nameservers": nameservers, "raw": result["stdout"]})


@network_bp.route("/dns", methods=["PUT"])
@jwt_required()
def set_dns():
    """Set DNS nameservers."""
    data = request.get_json()
    nameservers = data.get("nameservers", [])

    content = "# Generated by EasyLin\n"
    for ns in nameservers:
        content += f"nameserver {ns}\n"

    result = run_host_command(f"echo '{content}' > /etc/resolv.conf")
    return jsonify({"success": result["returncode"] == 0})


@network_bp.route("/connections", methods=["GET"])
@jwt_required()
def list_connections():
    """List active network connections."""
    result = run_host_command("ss -tulnp 2>/dev/null | head -50")
    return jsonify({"output": result["stdout"]})


@network_bp.route("/interfaces/<iface>/config", methods=["GET"])
@jwt_required()
def get_interface_config(iface):
    """Attempt to read current configuration for an interface from netplan."""
    # This is a bit complex as there might be multiple files, 
    # but we check our own file first, then others.
    try:
        import yaml
        files = ["/etc/netplan/99-easylin.yaml", "/etc/netplan/01-netcfg.yaml", "/etc/netplan/50-cloud-init.yaml"]
        for f in files:
            res = run_host_command(f"cat {f}")
            if res["returncode"] == 0:
                cfg = yaml.safe_load(res["stdout"])
                if "network" in cfg and "ethernets" in cfg["network"] and iface in cfg["network"]["ethernets"]:
                    ifc = cfg["network"]["ethernets"][iface]
                    return jsonify({
                        "dhcp": ifc.get("dhcp4") == "yes" or ifc.get("dhcp4", True) is True,
                        "address": ifc.get("addresses", [""])[0],
                        "gateway": ifc.get("routes", [{}])[0].get("via", "") if ifc.get("routes") else "",
                        "dns": ", ".join(ifc.get("nameservers", {}).get("addresses", []))
                    })
    except:
        pass
    
    return jsonify({"dhcp": True, "address": "", "gateway": "", "dns": "8.8.8.8, 1.1.1.1"})


@network_bp.route("/interfaces/<iface>/config", methods=["POST"])
@jwt_required()
def configure_interface(iface):
    """Configure a network interface (DHCP or Static)."""
    data = request.get_json()
    use_dhcp = data.get("dhcp", True)
    address = data.get("address", "")  # e.g., 192.168.1.100/24
    gateway = data.get("gateway", "")
    dns = data.get("dns", ["8.8.8.8", "1.1.1.1"])

    # Basic validation for static IP
    if not use_dhcp:
        if not address or "/" not in address:
            return jsonify({"error": "Valid IP address with CIDR (e.g. /24) is required for static config"}), 400

    # Create a netplan configuration
    # Note: This targets Ubuntu/Debian with netplan.
    config = {
        "network": {
            "version": 2,
            "renderer": "networkd",
            "ethernets": {
                iface: {
                    "dhcp4": "yes" if use_dhcp else "no"
                }
            }
        }
    }

    if not use_dhcp:
        config["network"]["ethernets"][iface]["addresses"] = [address]
        if gateway:
            config["network"]["ethernets"][iface]["routes"] = [{"to": "default", "via": gateway}]
        if dns:
            config["network"]["ethernets"][iface]["nameservers"] = {"addresses": dns}

    # Convert to YAML manually to avoid external dependencies for simple structure
    import yaml
    yaml_content = yaml.dump(config, default_flow_style=False)

    # Write to a netplan file (this will override or coexist depending on filename)
    # We use 99-easylin.yaml to ensure it takes precedence
    file_path = "/etc/netplan/99-easylin.yaml"
    write_res = run_host_command(f"cat > {file_path} << 'EOF'\n{yaml_content}\nEOF")

    if write_res["returncode"] != 0:
        return jsonify({"error": f"Failed to write netplan file: {write_res['stderr']}"}), 500

    # Apply netplan
    # WARNING: This might disconnect the user!
    apply_res = run_host_command("netplan apply", timeout=10)

    return jsonify({
        "success": True,
        "message": "Network configuration applied. Note: If you changed the IP, you might need to reconnect.",
        "output": apply_res["stdout"]
    })


@network_bp.route("/ping", methods=["POST"])
@jwt_required()
def ping_host():
    """Ping a host."""
    data = request.get_json()
    host = data.get("host", "").strip()
    if not host:
        return jsonify({"error": "Host is required"}), 400

    result = run_host_command(f"ping -c 4 -W 2 {host}", timeout=15)
    return jsonify({
        "success": result["returncode"] == 0,
        "output": result["stdout"],
    })
